// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPNWwkiFRMPUwWiaBIDGBs9n72rV4sl4',
    appId: '1:824646744879:android:79b2e191970fe2ab18bfda',
    messagingSenderId: '824646744879',
    projectId: 'omi-tests-13bcb',
    storageBucket: 'omi-tests-13bcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPNWwkiFRMPUwWiaBIDGBs9n72rV4sl4',
    appId: '1:824646744879:ios:3bea63d8e4f41dbfafb513',
    messagingSenderId: '824646744879',
    projectId: 'omi-tests-13bcb',
    storageBucket: 'omi-tests-13bcb.firebasestorage.app',
    androidClientId: '',
    iosClientId: '',
    iosBundleId: 'com.friend-app-with-wearable.ios12.development',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPNWwkiFRMPUwWiaBIDGBs9n72rV4sl4',
    appId: '1:824646744879:web:temp',
    messagingSenderId: '824646744879',
    projectId: 'omi-tests-13bcb',
    authDomain: 'omi-tests-13bcb.firebaseapp.com',
    storageBucket: 'omi-tests-13bcb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPNWwkiFRMPUwWiaBIDGBs9n72rV4sl4',
    appId: '1:824646744879:ios:3bea63d8e4f41dbfafb513',
    messagingSenderId: '824646744879',
    projectId: 'omi-tests-13bcb',
    storageBucket: 'omi-tests-13bcb.firebasestorage.app',
    androidClientId: '',
    iosClientId: '',
    iosBundleId: 'com.friend-app-with-wearable.ios12.development',
  );
}
